#!/usr/bin/env ruby
require 'web'
# Daemons sets pwd to /, so we have to explicitly set RAILS_ROOT
RAILS_ROOT = File.expand_path(File.dirname(__FILE__))

require File.join(File.dirname(__FILE__), *%w(lib delayed command))
Delayed::Command.new(ARGV).daemonize
